module.exports = RolesAndPrivilages = [
  {
      id: "ROLE_ADMIN_ADMIN",
      roleName: "ROLE_ADMIN_ADMIN",
      type: "generic",
      description: "Role with ROLE_ADMIN_ADMIN has the privileges ",
      privileges: [
        "PRIVILEGE_ACCOUNT_VIEW","PRIVILEGE_ACCOUNT_MANAGE","PRIVILEGE_NETWORK_DEVICE_VIEW","PRIVILEGE_NETWORK_DEVICE_MANAGE","PRIVILEGE_USER_ROLES_MANAGE","PRIVILEGE_GROUP_ACCOUNT_MANAGE","PRIVILEGE_ACCESS_POINT_VIEW","PRIVILEGE_ACCESS_POINT_MANAGE","PRIVILEGE_ADVERTISEMENT_MANAGE","PRIVILEGE_BUSINESS_ANALYTICS_VIEW","PRIVILEGE_DISPLAY_TERMINAL_VIEW,PRIVILEGE_DISPLAY_TERMINAL_MANAGE","PRIVILEGE_SETTINGS_VIEW","PRIVILEGE_SETTINGS_MANAGE","PRIVILEGE_VENUE_VIEW","PRIVILEGE_VENUE_MANAGE","PRIVILEGE_AUDIT_LOG_VIEW","PRIVILEGE_API_DOCS_ACCESS","PRIVILEGE_REPORT_VIEW","PRIVILEGE_REPORT_MANAGE","PRIVILEGE_IMAGE_SENSOR_VIEW,PRIVILEGE_IMAGE_SENSOR_MANAGE,PRIVILEGE_AAA_VIEW,PRIVILEGE_AAA_MANAGE,PRIVILEGE_CP_VIEW,PRIVILEGE_CP_MANAGE,PRIVILEGE_GUEST_VIEW,PRIVILEGE_GUEST_MANAGE,PRIVILEGE_DISPLAY_AUTHOR,PRIVILEGE_DISPLAY_PUBLISHER",
      ],

  },
  {
      id: "ROLE_ADMIN_DISTRIBUTOR",
      roleName: "ROLE_ADMIN_DISTRIBUTOR",
      type: "generic",
      description: "Role with ROLE_ADMIN_DISTRIBUTOR has the privileges ",
      privileges: [
        "PRIVILEGE_ACCOUNT_VIEW,PRIVILEGE_ACCOUNT_MANAGE,PRIVILEGE_NETWORK_DEVICE_VIEW,PRIVILEGE_NETWORK_DEVICE_MANAGE,PRIVILEGE_USER_ROLES_MANAGE,PRIVILEGE_GROUP_ACCOUNT_MANAGE,PRIVILEGE_ACCESS_POINT_VIEW,PRIVILEGE_ACCESS_POINT_MANAGE,PRIVILEGE_ADVERTISEMENT_MANAGE,PRIVILEGE_BUSINESS_ANALYTICS_VIEW,PRIVILEGE_DISPLAY_TERMINAL_VIEW,PRIVILEGE_DISPLAY_TERMINAL_MANAGE,PRIVILEGE_SETTINGS_VIEW,PRIVILEGE_SETTINGS_MANAGE,PRIVILEGE_VENUE_VIEW,PRIVILEGE_VENUE_MANAGE,PRIVILEGE_AUDIT_LOG_VIEW,PRIVILEGE_API_DOCS_ACCESS,PRIVILEGE_REPORT_VIEW,PRIVILEGE_REPORT_MANAGE,PRIVILEGE_IMAGE_SENSOR_VIEW,PRIVILEGE_IMAGE_SENSOR_MANAGE,PRIVILEGE_AAA_VIEW,PRIVILEGE_AAA_MANAGE,PRIVILEGE_CP_VIEW,PRIVILEGE_CP_MANAGE,PRIVILEGE_GUEST_VIEW,PRIVILEGE_GUEST_MANAGE,PRIVILEGE_DISPLAY_AUTHOR,PRIVILEGE_DISPLAY_PUBLISHER",
      ],
    },
    {
      id: "ROLE_ADMIN_USER",
      roleName: "ROLE_ADMIN_USER",
      type: "generic",
      description: "Role with ROLE_ADMIN_USER has the privileges ",
      privileges: [
        "PRIVILEGE_ACCOUNT_VIEW,PRIVILEGE_ACCOUNT_MANAGE,PRIVILEGE_NETWORK_DEVICE_VIEW,PRIVILEGE_NETWORK_DEVICE_MANAGE,PRIVILEGE_USER_ROLES_MANAGE,PRIVILEGE_GROUP_ACCOUNT_MANAGE,PRIVILEGE_ACCESS_POINT_VIEW,PRIVILEGE_ACCESS_POINT_MANAGE,PRIVILEGE_ADVERTISEMENT_MANAGE,PRIVILEGE_BUSINESS_ANALYTICS_VIEW,PRIVILEGE_DISPLAY_TERMINAL_VIEW,PRIVILEGE_DISPLAY_TERMINAL_MANAGE,PRIVILEGE_SETTINGS_VIEW,PRIVILEGE_SETTINGS_MANAGE,PRIVILEGE_VENUE_VIEW,PRIVILEGE_VENUE_MANAGE,PRIVILEGE_AUDIT_LOG_VIEW,PRIVILEGE_API_DOCS_ACCESS,PRIVILEGE_REPORT_VIEW,PRIVILEGE_REPORT_MANAGE,PRIVILEGE_IMAGE_SENSOR_VIEW,PRIVILEGE_IMAGE_SENSOR_MANAGE,PRIVILEGE_AAA_VIEW,PRIVILEGE_AAA_MANAGE,PRIVILEGE_CP_VIEW,PRIVILEGE_CP_MANAGE,PRIVILEGE_GUEST_VIEW,PRIVILEGE_GUEST_MANAGE,PRIVILEGE_DISPLAY_AUTHOR,PRIVILEGE_DISPLAY_PUBLISHER",
      ],
    },
];

// {
//   id: 'ROLE_ADMIN_ADMIN',
//   roleName: 'ROLE_ADMIN_ADMIN',
//   type: 'generic',
//   description: 'Role with ROLE_ADMIN_ADMIN has the privileges ',
//   privileges: [
//       'PRIVILEGE_ACCOUNT_VIEW,PRIVILEGE_ACCOUNT_MANAGE,PRIVILEGE_NETWORK_DEVICE_VIEW,PRIVILEGE_NETWORK_DEVICE_MANAGE,PRIVILEGE_USER_ROLES_MANAGE,PRIVILEGE_GROUP_ACCOUNT_MANAGE,PRIVILEGE_ACCESS_POINT_VIEW,PRIVILEGE_ACCESS_POINT_MANAGE,PRIVILEGE_ADVERTISEMENT_MANAGE,PRIVILEGE_BUSINESS_ANALYTICS_VIEW,PRIVILEGE_DISPLAY_TERMINAL_VIEW,PRIVILEGE_DISPLAY_TERMINAL_MANAGE,PRIVILEGE_SETTINGS_VIEW,PRIVILEGE_SETTINGS_MANAGE,PRIVILEGE_VENUE_VIEW,PRIVILEGE_VENUE_MANAGE,PRIVILEGE_AUDIT_LOG_VIEW,PRIVILEGE_API_DOCS_ACCESS,PRIVILEGE_REPORT_VIEW,PRIVILEGE_REPORT_MANAGE,PRIVILEGE_IMAGE_SENSOR_VIEW,PRIVILEGE_IMAGE_SENSOR_MANAGE,PRIVILEGE_AAA_VIEW,PRIVILEGE_AAA_MANAGE,PRIVILEGE_CP_VIEW,PRIVILEGE_CP_MANAGE,PRIVILEGE_GUEST_VIEW,PRIVILEGE_GUEST_MANAGE,PRIVILEGE_DISPLAY_AUTHOR,PRIVILEGE_DISPLAY_PUBLISHER',
//   ],
// },
