module.exports = User = {
    accessAccounts: ["string"],
    accessType: "string",
    accountUser: true,
    accounts: ["string"],
    createdBy: "string",
    createdTime: 0,
    email: "ritesh@gmail.com",
    expiryTime: 0,
    id: "string",
    lastUpdatedBy: "string",
    lastUpdatedTime: 0,
    location: {
      address: "string",
      city: "string",
      continentName: "string",
      countryCode: "string",
      countryName: "string",
      isp: "string",
      latitude: 0,
      longitude: 0,
      regionName: "string",
      timezone: "string",
      zip: "string",
    },
    name: "Ritesh Kumar",
    password: "Ritesh@123",
    passwordChangeKey: "string",
    passwordResetKey: "string",
    roles: ["ROLES_ADMIN_MANAGER"],
    salt: "string",
    status: "string",
    theme: "DARK",
    token: "string",
  }